# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/uptake',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/uptake',
                'lib_path': 'uptake'},
  'syms': {'uptake.loading': {'uptake.loading.load_vnklm': ('loading.html#load_vnklm', 'uptake/loading.py')}}}
