# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/uptake',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/uptake',
                'lib_path': 'uptake'},
  'syms': {'uptake.core': {'uptake.core.foo': ('core.html#foo', 'uptake/core.py')}}}
