# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_loading.ipynb.

# %% auto 0
__all__ = ['load_vnklm']

# %% ../nbs/00_loading.ipynb 3
import fastcore.all as fc
from pathlib import Path
import pandas as pd

# %% ../nbs/00_loading.ipynb 4
def load_vnklm():
    "Load Margot Vanheukelom KULeuven data."
    fname = Path('../_data/Margot_clean-data.xlsx')
    df = pd.read_excel(fname, nrows=207)
    
    coi = ['reference', 'soil code', 'dataset', 
           'soil class (WRB)', 'clay (%)', 'SOC (%)',
           'pH', 'CEC (cmolc/kg)', 'exchK (cmolc/kg)',
           'NH4ss (mmol/L)', 'contact time (d)', 'CR (kg/kg)',
           'predicted CR (kg/kg) Absalom1999', 
           'predicted CR (kg/kg) Absalom2001',
           'predicted CR (kg/kg) Tarsitano2011']
    
    names = ['ref', 'soil_code', 'ds', 'soil_class', 
             'clay', 'soc', 'ph', 'cec', 'kex', 'nh4',
             'time', 'cr', 'cr_absa_1999', 'cr_absa_2001', 'cr_tars_2011']
    
    df = df[coi]
    df.columns = names
    df = df.dropna(subset=['cr'])
    df = df[df['soil_class'] != "/"]
    
    col_features = ['clay', 'soc', 'cec', 'ph', 'kex', 'nh4', 'time']
    col_target = ['cr']
    return df
